@host = http://localhost:3000


### ADMIN CREATE CATEGORIES

POST {{host}}/api/admin/categories HTTP/1.1
Content-Type: multipart/form-data; boundary=simple

--simple
Content-Disposition: form-data; name="name.en"

Electronics
--simple
Content-Disposition: form-data; name="name.ar"

إلكترونيات
--simple
Content-Disposition: form-data; name="isVisible"

true
--simple--
